filter:
    paths:
        - src/*
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - '*Test.php'

tools:
    php_cs_fixer: true
    php_analyzer: true
    php_mess_detector: true
    php_changetracking: true
    php_code_sniffer: true
    php_pdepend: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_sim: true
    php_cpd: true

checks:
    php:
        code_rating: true
