language: php

# faster builds on docker-container setup
sudo: false

# used for HHVM
addons:
  apt:
    packages:
      - tidy

# cache vendor dirs
cache:
    apt: true
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: CS_FIXER=run
    allow_failures:
        - php: nightly

before_script:
    - PHP=$TRAVIS_PHP_VERSION
    - if [[ ! $PHP = hhvm* ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    # xdebug isn't enable for PHP 7.1
    - if [[ ! $PHP = hhvm* ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;
    - composer self-update --no-progress

script:
    - travis_wait bash composer install -o  --no-interaction --no-progress --prefer-dist
    - if [[ $CS_FIXER = run ]]; then php ./vendor/bin/php-cs-fixer fix src/ --verbose --dry-run ; fi;
    - if [[ ! $PHP = 5* ]]; then ./vendor/bin/phpunit; fi;
