##
# This file is part of the fnayou/dotted package.
#
# Copyright (c) 2016. Aymen FNAYOU <fnayou.aymen@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

version: '3.7'
services:
    # nginx
    nginx:
        container_name: dotted_nginx
        image: nginx
        expose:
            - "80"
        volumes:
            - ./docker/nginx/nginx.conf:/nginx.conf
            - ./docker/logs/nginx:/var/log/nginx
            - ./:/var/www/html
        environment:
            - VIRTUAL_HOST=dotted.loc
        depends_on:
            - php
        command: nginx -c /nginx.conf
        networks:
            dotted_network:
                ipv4_address: 172.13.10.3
    # php
    php:
        container_name: dotted_php
        build:
            context: docker/php
            dockerfile: Dockerfile
        expose:
            - 8000
        volumes:
            - ./docker/bash/bash_profile:/root/.bash_profile
            - ./docker/bash/bashrc:/root/.bashrc
            - ./docker/bash/bash_aliases:/root/.bash_aliases
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            dotted_network:
                ipv4_address: 172.13.10.4
networks:
    dotted_network:
        ipam:
            driver: default
            config:
                - subnet: "172.13.10.0/24"
