# source bashrc if exist
if [ -n "$BASH_VERSION" ]; then
 # include .bashrc if it exists
 if [ -f ~/.bashrc ]; then
   . ~/.bashrc
 fi
fi
# source git-completion if exist
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"